version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "6060:6060"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5435/app_db
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=app_pass
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
      
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    networks:
      - app-network
      
volumes:
  db_data:
      
networks:
  app-network:
    driver: bridge
