version: '3.8'

services:
  backend:
    build:
      context: ./flask-api
    ports:
      - "5050:5050"
    networks:
      - app-network

  frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
